In [1]:
import tensorflow as tf

In [2]:
print("tensorflow version :{}".format(tf.__version__))

tensorflow version :2.0.0


In [3]:
import numpy as np
np.set_printoptions(precision=3)

# 1.Creating tensors in Tensorflow

In [4]:
a = np.arange(1,6)
a = a.astype(np.float64)

b = np.linspace(1,10,10).astype(np.int32)

In [5]:
print(a, a.dtype)

[1. 2. 3. 4. 5.] float64


In [6]:
print(b, b.dtype)

[ 1  2  3  4  5  6  7  8  9 10] int32


## 1.1 converting from array to tensor

In [7]:
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

In [8]:
print(t_a)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float64)


In [9]:
print(t_b)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)


## 1.2 Built-in function 

In [10]:
t_ones = tf.ones((2,3))
print(t_ones)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [11]:
t_zeros = tf.zeros((3,2), dtype = tf.int32)
print(t_zeros)

tf.Tensor(
[[0 0]
 [0 0]
 [0 0]], shape=(3, 2), dtype=int32)


In [12]:
t = tf.random.uniform(shape=(3,5))
print(t)

tf.Tensor(
[[0.048 0.77  0.642 0.894 0.535]
 [0.726 0.18  0.944 0.354 0.733]
 [0.069 0.76  0.204 0.472 0.716]], shape=(3, 5), dtype=float32)


In [13]:
t_tr = tf.transpose(t)
print(t_tr)

tf.Tensor(
[[0.048 0.726 0.069]
 [0.77  0.18  0.76 ]
 [0.642 0.944 0.204]
 [0.894 0.354 0.472]
 [0.535 0.733 0.716]], shape=(5, 3), dtype=float32)


In [14]:
print(t.shape, ' --> ', t_tr.shape)

(3, 5)  -->  (5, 3)


In [15]:
t_zeros = tf.zeros((30,))
print("original ",t_zeros, end = '\n\n')
t_reshape = tf.reshape(t_zeros, shape=(5,6))
print("re-shaped ", t_reshape)

original  tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.], shape=(30,), dtype=float32)

re-shaped  tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(5, 6), dtype=float32)


## 1.3 Removing unnecessary dimensions - `squeeze`

In [16]:
t = tf.zeros((1,2,1,4,1))
print(t)

tf.Tensor(
[[[[[0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]]]]], shape=(1, 2, 1, 4, 1), dtype=float32)


In [17]:
t_sqz = tf.squeeze(t, axis = (2,4))
print(t_sqz)

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(1, 2, 4), dtype=float32)


## 1.4 Accessing elements in tensor

In [18]:
# to access on the values out of tensor
t_zeros.numpy()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [19]:
# to access on the values out of tensor
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [20]:
t_ones.shape

TensorShape([2, 3])

## 1.5 changing datatype

In [21]:
t_a_new = tf.cast(t_a, tf.int64)
print(t_a_new)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)


# 2. Mathematical operations to tensors

In [22]:
tf.random.set_seed(1)

## 2.1 Built in mathematical functions

In [23]:
# creating tensor with uniform distribution between -1.0 and 1.0
t1 = tf.random.uniform(shape = (5,2), minval = -1.0, maxval = 1.0)
print(t1)

tf.Tensor(
[[-0.67   0.803]
 [ 0.262 -0.131]
 [-0.416  0.285]
 [ 0.952 -0.13 ]
 [ 0.32   0.21 ]], shape=(5, 2), dtype=float32)


In [24]:
# creating tensor with Gaussian distribution
t2 = tf.random.normal(shape = (5,2), mean = 0.0, stddev = 1.0)
print(t2)

tf.Tensor(
[[ 0.403 -1.088]
 [-0.063  1.337]
 [ 0.712 -0.489]
 [-0.764 -1.037]
 [-1.252  0.021]], shape=(5, 2), dtype=float32)


In [25]:
t3 = tf.multiply(t1, t2).numpy() # element-wise multiplication
print(t3)

[[-0.27  -0.874]
 [-0.017 -0.175]
 [-0.296 -0.139]
 [-0.727  0.135]
 [-0.401  0.004]]


In [26]:
t4 = tf.add(t1,t2).numpy()
print(t4)

[[-0.267 -0.285]
 [ 0.199  1.206]
 [ 0.296 -0.204]
 [ 0.187 -1.167]
 [-0.932  0.231]]


In [27]:
t5 = tf.divide(t1,t2).numpy()
print(t5)

[[-1.662 -0.738]
 [-4.152 -0.098]
 [-0.585 -0.582]
 [-1.245  0.125]
 [-0.256  9.885]]


In [28]:
t6 = tf.subtract(t1,t2).numpy()
print(t6)

[[-1.073  1.891]
 [ 0.325 -1.467]
 [-1.128  0.774]
 [ 1.716  0.907]
 [ 1.572  0.189]]


In [29]:
# to extract 1st column
t3[:, 0] 

array([-0.27 , -0.017, -0.296, -0.727, -0.401], dtype=float32)

## 2.2 Computing mean(), sum(), standard deviation along axis

In [30]:
t_reduce_mean = tf.math.reduce_mean(t1, axis = 0)  # axis = 0 means along the columns
print(t_reduce_mean)
t_reduce_mean.numpy()

tf.Tensor([0.09  0.207], shape=(2,), dtype=float32)


array([0.09 , 0.207], dtype=float32)

In [31]:
tf.math.reduce_sum(t1, axis = 1)

<tf.Tensor: id=48, shape=(5,), dtype=float32, numpy=array([ 0.133,  0.131, -0.131,  0.822,  0.53 ], dtype=float32)>

In [32]:
tf.math.reduce_std(t1, axis = 0).numpy()

array([0.576, 0.343], dtype=float32)

In [33]:
tf.math.reduce_prod(t1, axis = 0).numpy()

array([0.022, 0.001], dtype=float32)

In [34]:
# matrix-matrix multiplication
t5 = tf.linalg.matmul(t1, t2, transpose_b = True)
print(t5.numpy())

[[-1.144  1.115 -0.87  -0.321  0.856]
 [ 0.248 -0.191  0.25  -0.064 -0.331]
 [-0.478  0.407 -0.436  0.022  0.527]
 [ 0.525 -0.234  0.741 -0.593 -1.194]
 [-0.099  0.26   0.125 -0.462 -0.396]]


In [35]:
t6 = tf.linalg.matmul(t1, t2, transpose_a = True)
print(t6.numpy())

[[-1.711  0.302]
 [ 0.371 -1.049]]


## 2.3 Calculating the norm of the tensor

In [36]:
print(t1)

tf.Tensor(
[[-0.67   0.803]
 [ 0.262 -0.131]
 [-0.416  0.285]
 [ 0.952 -0.13 ]
 [ 0.32   0.21 ]], shape=(5, 2), dtype=float32)


In [37]:
# norm 2 (L-2 norm) of the tensor t1
norm_t1 = tf.norm(t1, ord = 2, axis = 1).numpy()
print(norm_t1)

[1.046 0.293 0.504 0.96  0.383]


 $l_2-norm:\sqrt(x_i^2 + y_i^2)$

In [38]:
np.sqrt(np.sum(np.square(t1), axis = 1))

array([1.046, 0.293, 0.504, 0.96 , 0.383], dtype=float32)

In [39]:
# norm 1 (L-1 norm) of the tensor t1
l1_norm_t1 = tf.norm(t1, ord = 1, axis = 1).numpy()
print(l1_norm_t1)

[1.473 0.393 0.701 1.081 0.53 ]


$l_1- norm : \sum_{x=1}^{n}|x|$

In [40]:
np.sum(np.abs(t1), axis = 1)

array([1.473, 0.393, 0.701, 1.081, 0.53 ], dtype=float32)

# 3. Split, Stack and Concatenate tensors

## 3.1 Split

In [41]:
t = tf.random.uniform(shape = (6,), minval = -1, maxval = 1)
print(t.numpy())

[ 0.659  0.268  0.029 -0.218  0.162 -0.903]


In [42]:
t_splits = tf.split(t, num_or_size_splits=3)
print(t_splits) # list with partition
[ item.numpy() for item in t_splits]

[<tf.Tensor: id=78, shape=(2,), dtype=float32, numpy=array([0.659, 0.268], dtype=float32)>, <tf.Tensor: id=79, shape=(2,), dtype=float32, numpy=array([ 0.029, -0.218], dtype=float32)>, <tf.Tensor: id=80, shape=(2,), dtype=float32, numpy=array([ 0.162, -0.903], dtype=float32)>]


[array([0.659, 0.268], dtype=float32),
 array([ 0.029, -0.218], dtype=float32),
 array([ 0.162, -0.903], dtype=float32)]

In [43]:
print(t_splits[0].numpy())
print(t_splits[1].numpy())
print(t_splits[2].numpy())

[0.659 0.268]
[ 0.029 -0.218]
[ 0.162 -0.903]


In [44]:
# generates list with specified dimensions
t_splits

[<tf.Tensor: id=78, shape=(2,), dtype=float32, numpy=array([0.659, 0.268], dtype=float32)>,
 <tf.Tensor: id=79, shape=(2,), dtype=float32, numpy=array([ 0.029, -0.218], dtype=float32)>,
 <tf.Tensor: id=80, shape=(2,), dtype=float32, numpy=array([ 0.162, -0.903], dtype=float32)>]

In [45]:
t_size_splits = tf.split(t, num_or_size_splits= [4,2])
[ item.numpy() for item in t_size_splits ]

[array([ 0.659,  0.268,  0.029, -0.218], dtype=float32),
 array([ 0.162, -0.903], dtype=float32)]

## 3.2 Concatenate

In [46]:
A = tf.ones((3,))
B = tf.zeros((2,))
C = tf.concat([A, B], axis = 0)

print("A:",A.numpy())
print("B:",B.numpy())
print("C:",C.numpy())

A: [1. 1. 1.]
B: [0. 0.]
C: [1. 1. 1. 0. 0.]


## 3.3 Stack

In [47]:
A = tf.ones((3,))
B = tf.zeros((3,))

C = tf.stack([A, B], axis = 1)
print(C)

tf.Tensor(
[[1. 0.]
 [1. 0.]
 [1. 0.]], shape=(3, 2), dtype=float32)


# 4. Building input pipelines using tf.data

- when dataset is very huge to fit in computer memory, we have to load the data in batch by batch from hard drive or solid state device
- otherwise tf.keras `fit()` method is sufficient to load the data

## 4.1 to create slices from dataset

In [48]:
a = [1.2, 3.4, 7.5, 4.1, 5.0, 1.0]

ds = tf.data.Dataset.from_tensor_slices(a)
print(ds)

<TensorSliceDataset shapes: (), types: tf.float32>


In [49]:
for item in ds:
    print(item.numpy())

1.2
3.4
7.5
4.1
5.0
1.0


In [50]:
for item in ds:
    print(item)

tf.Tensor(1.2, shape=(), dtype=float32)
tf.Tensor(3.4, shape=(), dtype=float32)
tf.Tensor(7.5, shape=(), dtype=float32)
tf.Tensor(4.1, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


## 4.2 to create the batches from the dataset

In [51]:
ds_batch = ds.batch(batch_size=3)
for i, elem in enumerate(ds_batch):
    print(f'batch {i}:', elem.numpy())

batch 0: [1.2 3.4 7.5]
batch 1: [4.1 5.  1. ]


In [52]:
ds_1 = np.arange(1,20)
ds_1_batch = tf.data.Dataset.from_tensor_slices(ds_1).batch(batch_size=5, drop_remainder= False)
for i, elem in enumerate(ds_1_batch):
    print(f'batch {i}:', elem.numpy())

batch 0: [1 2 3 4 5]
batch 1: [ 6  7  8  9 10]
batch 2: [11 12 13 14 15]
batch 3: [16 17 18 19]


## 4.3 combine two tensors into a joint datasets

In [53]:
tf.random.set_seed(1)
t_x = tf.random.uniform((4,3), minval = -1.0, maxval = 1.0, dtype = tf.float32)
t_y = tf.range(4)

In [54]:
print('t_x:\n', t_x.numpy(), end = '\n\n')
print('t_y:\n', t_y.numpy())

t_x:
 [[-0.67   0.803  0.262]
 [-0.131 -0.416  0.285]
 [ 0.952 -0.13   0.32 ]
 [ 0.21   0.273  0.229]]

t_y:
 [0 1 2 3]


In [55]:
ds_x = tf.data.Dataset.from_tensor_slices(t_x) # consider as features
ds_y = tf.data.Dataset.from_tensor_slices(t_y) # consider as labels / target
ds_joint = tf.data.Dataset.zip((ds_x, ds_y))
print(ds_joint)

<ZipDataset shapes: ((3,), ()), types: (tf.float32, tf.int32)>


In [56]:
for eg in ds_joint:
    print('x:', eg[0].numpy(), '  y:', eg[1].numpy())

x: [-0.67   0.803  0.262]   y: 0
x: [-0.131 -0.416  0.285]   y: 1
x: [ 0.952 -0.13   0.32 ]   y: 2
x: [0.21  0.273 0.229]   y: 3


In [57]:
# alternative to above
ds_joint_alt = tf.data.Dataset.from_tensor_slices((t_x, t_y))
for eg in ds_joint_alt:
    print('x:', eg[0].numpy(), '  y:', eg[1].numpy())

x: [-0.67   0.803  0.262]   y: 0
x: [-0.131 -0.416  0.285]   y: 1
x: [ 0.952 -0.13   0.32 ]   y: 2
x: [0.21  0.273 0.229]   y: 3


## 4.4 transformation on dataset from two tensors

In [58]:
ds_trans = ds_joint.map(lambda x,y: ( abs(x*2 - 1.0), y ) )
for eg in ds_trans:
    print('x:', eg[0].numpy(), '  y:', eg[1].numpy())

x: [2.339 0.606 0.476]   y: 0
x: [1.262 1.832 0.43 ]   y: 1
x: [0.903 1.26  0.36 ]   y: 2
x: [0.58  0.453 0.542]   y: 3


## 4.5 shuffle

- `.shuffle()` method requires an argument called `buffer_size`, which is determines how many elememts in the dataset are grouped together before shuffling.
- if dataset is small, choosing the small `buffer_size` negatively affects the predictive performance of the neural-net as the dataset may not be completely randomized

In [59]:
# Rows are shuffled without loosing one to one correspondence between the entries x and y.
# to ensure the complete randomized dataset, set buffer_size = length of traning data
ds_2 = ds_joint.shuffle(buffer_size=len(t_x))
for eg in ds_2:
    print('x:', eg[0].numpy(), '  y:', eg[1].numpy())

x: [-0.131 -0.416  0.285]   y: 1
x: [ 0.952 -0.13   0.32 ]   y: 2
x: [0.21  0.273 0.229]   y: 3
x: [-0.67   0.803  0.262]   y: 0


In [60]:
# Rows are shuffled without loosing one to one correspondence between the entries x and y.
ds_3 = ds_joint.shuffle(buffer_size=len(t_y))
for eg in ds_3:
    print('x:', eg[0].numpy(), '  y:', eg[1].numpy())

x: [ 0.952 -0.13   0.32 ]   y: 2
x: [-0.131 -0.416  0.285]   y: 1
x: [-0.67   0.803  0.262]   y: 0
x: [0.21  0.273 0.229]   y: 3


In [61]:
# Rows are shuffled without loosing one to one correspondence between the entries x and y.
ds_3 = ds_joint.shuffle(buffer_size= 5)
for eg in ds_3:
    print('x:', eg[0].numpy(), '  y:', eg[1].numpy())

x: [-0.67   0.803  0.262]   y: 0
x: [-0.131 -0.416  0.285]   y: 1
x: [0.21  0.273 0.229]   y: 3
x: [ 0.952 -0.13   0.32 ]   y: 2


In [73]:
ds_3 = ds_joint.repeat(count= 2)
for eg in ds_3:
    print('x:', eg[0].numpy(), '  y:', eg[1].numpy())

x: [-0.67   0.803  0.262]   y: 0
x: [-0.131 -0.416  0.285]   y: 1
x: [ 0.952 -0.13   0.32 ]   y: 2
x: [0.21  0.273 0.229]   y: 3
x: [-0.67   0.803  0.262]   y: 0
x: [-0.131 -0.416  0.285]   y: 1
x: [ 0.952 -0.13   0.32 ]   y: 2
x: [0.21  0.273 0.229]   y: 3


## 4.6+ Batch

In [62]:
ds = ds_joint.batch(3, drop_remainder=False)
batch_x, batch_y = next(iter(ds))


In [63]:
batch_x

<tf.Tensor: id=300, shape=(3, 3), dtype=float32, numpy=
array([[-0.67 ,  0.803,  0.262],
       [-0.131, -0.416,  0.285],
       [ 0.952, -0.13 ,  0.32 ]], dtype=float32)>

In [64]:
batch_y

<tf.Tensor: id=301, shape=(3,), dtype=int32, numpy=array([0, 1, 2])>

In [65]:
for i in ds:
    print(i)

(<tf.Tensor: id=307, shape=(3, 3), dtype=float32, numpy=
array([[-0.67 ,  0.803,  0.262],
       [-0.131, -0.416,  0.285],
       [ 0.952, -0.13 ,  0.32 ]], dtype=float32)>, <tf.Tensor: id=308, shape=(3,), dtype=int32, numpy=array([0, 1, 2])>)
(<tf.Tensor: id=309, shape=(1, 3), dtype=float32, numpy=array([[0.21 , 0.273, 0.229]], dtype=float32)>, <tf.Tensor: id=310, shape=(1,), dtype=int32, numpy=array([3])>)


In [71]:
ds_joint = tf.data.Dataset.from_tensor_slices((t_x, t_y))
print(t_x.shape)
print(t_y.shape)
print(ds_joint)

(4, 3)
(4,)
<TensorSliceDataset shapes: ((3,), ()), types: (tf.float32, tf.int32)>


In [67]:
# shuffle -> batch -> repeat
ds = ds_joint.shuffle(buffer_size = 4).batch(batch_size = 2).repeat(count = 3)
for i, (batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())

0 (2, 3) [0 2]
1 (2, 3) [1 3]
2 (2, 3) [1 0]
3 (2, 3) [2 3]
4 (2, 3) [3 1]
5 (2, 3) [0 2]


In [72]:
# batch -> shuffle -> repeat
ds = ds_joint.batch(batch_size = 2).shuffle(buffer_size = 4).repeat(count = 3)
for i, (batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())


0 (2, 3) [2 3]
1 (2, 3) [0 1]
2 (2, 3) [0 1]
3 (2, 3) [2 3]
4 (2, 3) [0 1]
5 (2, 3) [2 3]
